name: ci
on: push
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      # https://github.com/cypress-io/github-action
      - name: Run tests 🧪
        uses: cypress-io/github-action@v2
        with:
          start: npm run dev, npm run dev:api
        env:
          DB_HOST: '${{ secrets.DB_HOST }}'
          DB_NAME: '${{ secrets.DB_NAME }}'
          DB_USER: '${{ secrets.DB_USER }}'
          DB_PASSWORD: '${{ secrets.DB_PASSWORD }}'
          TEST_PHONE_NUMBER: '${{ secrets.TEST_PHONE_NUMBER }}'
          TEST_PHONE_NUMBER_PREFIX: '${{ secrets.TEST_PHONE_NUMBER_PREFIX }}'
